import Head from "next/head";
import HomePage from "@/views/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Red1 Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <>
        <HomePage />
      </>
    </>
  );
}
