import Layout from "@components/Layout";
import Home from "@views/Home";
import RightSidebar from "@views/Home/RightSidebar/RightSidebar";
import Head from "next/head";
import { ReactElement } from "react";
import { NextPageWithLayout } from "src/models/Global";

const HomePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Red1 Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <>
        <Home />
      </>
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout isRightSideBar={<RightSidebar />}>
      <div>{page}</div>
    </Layout>
  );
};

export default HomePage;
